CREATE TABLE [dbo].[Tenant]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY default NEWID(),
	[TenantId] UNIQUEIDENTIFIER NOT NULL,
	[Name] VARCHAR(100) NOT NULL,
	[Email] VARCHAR(100) NOT NULL,
	[Address] NVARCHAR(MAX) NULL CHECK(ISJSON(Address) = 1),
	[DateFormat] VARCHAR(20) NOT NULL,
	[IsActive] BIT NULL,
	[IsDeleted] BIT NULL,
	[CreatedBy] UNIQUEIDENTIFIER NOT NULL,
	[CreatedDate] DATETIMEOFFSET NOT NULL,
	[ModifiedBy] UNIQUEIDENTIFIER NOT NULL,
	[ModifiedDate] DATETIMEOFFSET NOT NULL
)

GO
CREATE NONCLUSTERED INDEX [EmailIndex]
    ON [dbo].[Tenant]([Email] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NameIndex]
    ON [dbo].[Tenant]([Name] ASC) WHERE ([Name] IS NOT NULL);
